const { URL } = require('url')
const url_1 = new URL('/foo', 'https://example.org/')
console.log(url_1)

const url_2 = new URL({ toString: () => 'https://example.org/' })
console.log(url_2)

const url_3 = new URL('https://你好你好')
console.log(url_3)

const myURL = new URL('https://example.org/foo#bar')
console.log('获取及设置URL的分段(hash)部分:', myURL.hash)
console.log('获取及设置URL的主机(host)部分:', myURL.host)
console.log('获取及设置URL的主机名(hostname)部分', myURL.hostname)
console.log('获取及设置序列化的URL', myURL.href)
console.log('获取只读序列化的URL origin部分', myURL.origin)
console.log('获取及设置URL的密码(password)部分', myURL.password)
console.log('获取及设置URL的路径(path)部分', myURL.pathname)
console.log('获取及设置URL的端口(port)部分', myURL.port)
console.log('获取及设置URL的协议(protocol)部分', myURL.protocol)
console.log('获取及设置URL的序列化查询(query)部分部分', myURL.search)
console.log('获取表示URL查询参数的URLSearchParams对象', myURL.searchParams)
console.log('获取及设置URL的用户名(username)部分', myURL.username)
console.log('在URL对象上调用toString()方法将返回序列化的URL', myURL.toString())
console.log('在URL对象上调用toJSON()方法将返回序列化的URL', myURL.toJSON())
