const fs = require('fs')

fs.stat(__dirname + '/txt/file.txt', (err, stats) => {
  if (!err) {
    console.log('对象是否为一个设备', stats.isBlockDevice())
    console.log('对象是否为一个字符设备', stats.isCharacterDevice())
    console.log('对象是否为一个文件系统目录', stats.isDirectory())
    console.log('对象是否为一个先进先出(FIFO)管道', stats.isFIFO())
    console.log('对象是否为一个普通文件', stats.isFile())
    console.log('对象是否为一个socket', stats.isSocket())
    console.log('对象是否为一个符号链接', stats.isSymbolicLink())
    console.log('文件所在的设备的数值型标识', stats.dev)
    console.log('文件系统特定的文件索引节点数值', stats.ino)
    console.log('文件类型与模式的位域', stats.mode)
    console.log('文件的硬链接数量', stats.nlink)
    console.log('文件所有者的数值型用户标识', stats.uid)
    console.log('文件的群组的数值型群组标识', stats.gid)
    console.log('文件的字节大小', stats.size)
    console.log('文件系统用于I/O操作的块大小', stats.blksize)
    console.log('分配给文件的块的数量', stats.blocks)
    console.log('文件最后一次被访问的时间戳', stats.atimeMs)
    console.log('文件最后一次被修改的时间戳', stats.ctimeMs)
    console.log('文件状态最后一次被修改的时间戳', stats.mtimeMs)
    console.log('文件的创建时间戳', stats.birthtimeMs)
    console.log('文件最后一次被访问的时间', stats.atime)
    console.log('文件最后一次被修改的时间', stats.mtime)
    console.log('文件状态最后一次被修改的时间', stats.ctime)
    console.log('文件的创建时间', stats.birthtime)
  }
})